config/routes.rb
Rails.application.routes.draw do
  resources :clients do 
    resources :sites do 
      resources :workorders
    end 
  end
  resources :technicians
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :sites
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :client
  has_many :workorders

  # CATEGORY_OPTIONS = [
  #   ['HVAC', 'HVAC'],
  #   ['REFRIGERATION', 'REFRIGERATION']
  # ]

end

app/models/technician.rb
class Technician < ApplicationRecord
    has_many :workorders
end

app/models/workorder.rb
class Workorder < ApplicationRecord
    belongs_to :site
    has_many :technicians

    CATEGORY_OPTIONS = [
    ['HVAC', 'HVAC'],
    ['REFRIGERATION', 'REFRIGERATION']
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :billing_address, :city, :state, :zip)
    end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_client 
  before_action :set_site, only: %i[ show edit update destroy ]
  # GET /sites or /sites.json

  def index
    @sites = @client.sites
  end

  # GET /sites/1 or /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = @client.sites.build
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites or /sites.json
  def create
    @site = @client.sites.build(site_params)
    
      if @site.save
        redirect_to(@site.client) 
      else
        render action: 'new'
    end
  end

  # PATCH/PUT /sites/1 or /sites/1.json
  def update
      if @site.update(site_params)
        redirect_to(@site.client)        
      else
        render action: 'edit'
      end
  end

  # DELETE /sites/1 or /sites/1.json
  def destroy
    @site.destroy
    redirect_to @client
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_client
      @client = Client.find(params[:client_id])
    end
    
    
    def set_site
      @site = @client.sites.find(params[:id])
    end


    # Only allow a list of trusted parameters through.
    def site_params
      params.require(:site).permit(:name, :number, :phone, :address, :city, :state, :zip, :acct_mgr, :branch_mgr, :client_id)
    end
end

app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController
  before_action :set_technician, only: %i[ show edit update destroy ]

  # GET /technicians or /technicians.json
  def index
    @technicians = Technician.all
  end

  # GET /technicians/1 or /technicians/1.json
  def show
  end

  # GET /technicians/new
  def new
    @technician = Technician.new
  end

  # GET /technicians/1/edit
  def edit
  end

  # POST /technicians or /technicians.json
  def create
    @technician = Technician.new(technician_params)

    respond_to do |format|
      if @technician.save
        format.html { redirect_to technician_url(@technician), notice: "Technician was successfully created." }
        format.json { render :show, status: :created, location: @technician }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @technician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technicians/1 or /technicians/1.json
  def update
    respond_to do |format|
      if @technician.update(technician_params)
        format.html { redirect_to technician_url(@technician), notice: "Technician was successfully updated." }
        format.json { render :show, status: :ok, location: @technician }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @technician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technicians/1 or /technicians/1.json
  def destroy
    @technician.destroy

    respond_to do |format|
      format.html { redirect_to technicians_url, notice: "Technician was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technician
      @technician = Technician.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def technician_params
      params.require(:technician).permit(:name, :tech_id, :phone, :email, :address)
    end
end

app/controllers/workorders_controller.rb
class WorkordersController < ApplicationController
  before_action :set_client
  before_action :set_site
  before_action :set_workorder, only: %i[ show edit update destroy ]

  # GET /workorders or /workorders.json
  def index
    @workorders = @site.workorders
  end

  # GET /workorders/1 or /workorders/1.json
  def show
  end

  # GET /workorders/new
  def new
    @workorder = @site.workorders.build
  end

  # GET /workorders/1/edit
  def edit
  end

  # POST /workorders or /workorders.json   @site = @client.sites.build(site_params)
  def create
    @workorder = @site.workorders.build(workorder_params)
      if @workorder.save
        redirect_to(@workorder.site)
      else
        render action: 'new'
      end
  end

  # PATCH/PUT /workorders/1 or /workorders/1.json
  def update
      if @workorder.update(workorder_params)
        redirect_to(@workorder.site)
      else
        render action: 'edit'
      end
  end

  # DELETE /workorders/1 or /workorders/1.json
  def destroy
    @workorder.destroy

    respond_to do |format|
      format.html { redirect_to workorders_url, notice: "Workorder was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workorder
      @workorder = @site.workorders.find(params[:id])
    end

    def set_client
      @client = Client.find(params[:client_id])
    end


    def set_site
      @site = Site.find(params[:site_id])
    end


    # Only allow a list of trusted parameters through.
    def workorder_params
      params.require(:workorder).permit(:category, :caller, :PO, :work_requested, :schedule_date, :completion_date, :site_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/helpers/workorders_helper.rb
module WorkordersHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Street %>
    <%= form.text_field :billing_address %>
  </div>

    <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

      <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

      <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>




  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Street</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.billing_address %></td>
        <td><%= client.city %></td>
        <td><%= client.state %></td>
        <td><%= client.zip %></td>

        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Street:</strong>
  <%= @client.billing_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @client.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @client.zip %>
</p>


<%= link_to "See All Sites", client_sites_path(@client) %> |
<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>


<h3>See All Workorders</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Service24</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sites/_form.html.erb
<%= form_for([@site.client, @site]) do |form| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
        <% site.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

    <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>


  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

    <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>



  <div class="field">
    <%= form.label :acct_mgr %>
    <%= form.select :acct_mgr, ['None', 'Mandee Maxey', 'Courtney Stewart', 'Kevin Longberry']  %>
  </div>

  <div class="field">
    <%= form.label :branch_mgr %>
    <%= form.select :branch_mgr, ['None', 'Ian McCurry', 'Josh Ramos', 'Bryan Hoffman', 'James McCrorey'] %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Show', client_site_path %> |
<%= link_to 'Back', client_sites_path %>

app/views/sites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Acct mgr<br></th>
      <th>Branch mgr</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.name %></td>
        <td><%= site.number %></td>
        <td><%= site.phone %></td>
        <td><%= site.address %></td>
        <td><%= site.acct_mgr %></td>
        <td><%= site.branch_mgr %></td>
        
        <td><%= link_to 'Edit', edit_client_site_path(@sites, @client) %></td>
        <td><%= link_to 'Destroy', [site.client, site], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Site', new_client_site_path %>

<h3>Workorders for Site</h3>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Back', client_sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @site.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @site.number %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @site.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @site.address %>
</p>

<p>
  <strong>Acct mgr:</strong>
  <%= @site.acct_mgr %>
</p>

<p>
  <strong>Branch mgr:</strong>
  <%= @site.branch_mgr %>
</p>


<%= link_to 'Edit', edit_client_site_path(@site) %> |
<%= link_to 'Back', client_sites_path %>

app/views/technicians/_form.html.erb
<%= form_with(model: technician) do |form| %>
  <% if technician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(technician.errors.count, "error") %> prohibited this technician from being saved:</h2>

      <ul>
        <% technician.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :tech_id %>
    <%= form.text_field :tech_id %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/technicians/edit.html.erb
<h1>Editing Technician</h1>

<%= render 'form', technician: @technician %>

<%= link_to 'Show', @technician %> |
<%= link_to 'Back', technicians_path %>

app/views/technicians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Technicians</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tech</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @technicians.each do |technician| %>
      <tr>
        <td><%= technician.name %></td>
        <td><%= technician.tech_id %></td>
        <td><%= technician.phone %></td>
        <td><%= technician.email %></td>
        <td><%= technician.address %></td>
        <td><%= link_to 'Show', technician %></td>
        <td><%= link_to 'Edit', edit_technician_path(technician) %></td>
        <td><%= link_to 'Destroy', technician, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Technician', new_technician_path %>

app/views/technicians/new.html.erb
<h1>New Technician</h1>

<%= render 'form', technician: @technician %>

<%= link_to 'Back', technicians_path %>

app/views/technicians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @technician.name %>
</p>

<p>
  <strong>Tech:</strong>
  <%= @technician.tech_id %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @technician.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @technician.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @technician.address %>
</p>

<%= link_to 'Edit', edit_technician_path(@technician) %> |
<%= link_to 'Back', technicians_path %>

app/views/workorders/_form.html.erb
<%= form_for([@client, @site, @workorder]) do |form| %>
  <% if workorder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workorder.errors.count, "error") %> prohibited this workorder from being saved:</h2>

      <ul>
        <% workorder.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, Workorder::CATEGORY_OPTIONS, {} %>
  </div>

    <div class="field">
    <%= form.label :caller %>
    <%= form.text_field :caller %>
  </div>


  <div class="field">
    <%= form.label :Customer_PO %>
    <%= form.text_field :PO %>
  </div>

  <div class="field">
    <%= form.label :work_requested %>
    <%= form.text_area :work_requested %>
  </div>

  <div class="field">
    <%= form.label :schedule_date %>
    <%= form.datetime_select :schedule_date %>
  </div>

  <div class="field">
    <%= form.label :completion_date %>
    <%= form.datetime_select :completion_date %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Workorder' %>
  </div>
<% end %>

app/views/workorders/edit.html.erb
<h1>Editing Workorder</h1>

<%= render 'form', workorder: @workorder %>

<%= link_to 'Show', client_site_workorder_path(@workorder) %> |
<%= link_to 'Back', client_site_workorders_path %>

app/views/workorders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workorders</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>caller</th>
      <%
=begin%>
 <th>Po</th> 
<%
=end%>
      <th>Work requested</th>
      <th>Schedule date</th>
      <th>Completion date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workorders.each do |workorder| %>
      <tr>
        <td><%= workorder.category %></td>
        <td><%= workorder.caller %></td>
        <td><%= workorder.PO %></td>
        <td><%= workorder.work_requested %></td>
        <td><%= workorder.schedule_date %></td>
        <td><%= workorder.completion_date %></td>
        <td><%= link_to 'Show', client_site_workorders_path(workorder) %></td>
        <%
=begin%>
 <td><%= link_to 'Edit', edit_client_site_workorder_path(@site, workorder) %></td> 
<%
=end%>
        <td><%= link_to 'Destroy', @workorder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workorder', new_client_site_workorder_path %>

app/views/workorders/new.html.erb
<h1>New Workorder</h1>

<%= render 'form', workorder: @workorder %>

<%= link_to 'Back', client_site_workorders_path %>

app/views/workorders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @workorder.category %>
</p>

<p>
  <strong>Caller:</strong>
  <%= @workorder.caller %>
</p>


<p>
  <strong>PO:</strong>
  <%= @workorder.PO %>
</p>

<p>
  <strong>Work requested:</strong>
  <%= @workorder.work_requested %>
</p>

<p>
  <strong>Schedule date:</strong>
  <%= @workorder.schedule_date %>
</p>

<p>
  <strong>Completion date:</strong>
  <%= @workorder.completion_date %>
</p>

<%= link_to 'Edit', edit_client_site_workorder_path(@workorder) %> |
<%= link_to 'Back', client_site_workorders_path %>